/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations, Html, Box } from "@react-three/drei";
import { MeshNormalMaterial } from "three";

export function ModelDetail(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/wall.glb");
  const { actions } = useAnimations(animations, group);
  console.log(materials);
  const [hover, setHover] = useState(false);

  const myNormal = new MeshNormalMaterial();

  return (
    <mesh
      name="Plane"
      castShadow
      receiveShadow
      geometry={nodes.DachZiegel001.geometry}
      material={!hover ? myNormal : nodes.DachZiegel001.material}
      position={nodes.DachZiegel001.position}
      onPointerOver={() => setHover(true)}
      onPointerLeave={() => setHover(false)}
    />
    // <Box />
  );
}

useGLTF.preload("/wall.glb");
